spring.application.name=machine-maintenance-portal

# Defaults work locally; override with environment variables (useful for Docker / Jenkins later)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/machine_maintenance}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Narsimha}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080
